"""
WP5 — regenerate the vault's navigation from front-matter (run after ANY memory edit):
  - 00 — Start Here/Welcome.md      : hub linking every top folder's MOC
  - <top folder>/_MOC.md            : table of that folder's docs (title, type, status, verdict, updated)
  - 00 — Start Here/INDEX.json      : machine-readable catalog for agents
  - 00 — Start Here/Dead-Ends Register.md : every status=dead doc, one line each

These four outputs are generated — never hand-edit them. Everything else is the source of truth.
Run from repo root: python scripts/memory/build_index.py
"""
import os, re, json

VAULT = 'finalgo-memory-layer/finalgo'
START = '00 — Start Here'
GENERATED = {'Welcome.md', '_MOC.md', 'Dead-Ends Register.md', 'INDEX.json'}

def parse_fm(txt):
    if not txt.lstrip().startswith('---'):
        return {}
    body = txt.split('---', 2)
    if len(body) < 3:
        return {}
    fm = {}
    for line in body[1].splitlines():
        m = re.match(r'(\w+):\s*(.*)$', line)
        if m:
            v = m.group(2).strip().strip('"')
            fm[m.group(1)] = v
    return fm

def first_para(txt):
    body = txt.split('---', 2)[-1] if txt.lstrip().startswith('---') else txt
    for line in body.splitlines():
        s = line.strip()
        if s and not s.startswith('#') and not s.startswith('>'):
            return re.sub(r'[\[\]`*]', '', s)[:140]
    return ''

# collect
docs = []
for root, _, files in os.walk(VAULT):
    if '.obsidian' in root:
        continue
    for f in files:
        if not f.endswith('.md') or f in GENERATED:
            continue
        p = os.path.join(root, f)
        rel = os.path.relpath(p, VAULT).replace('\\', '/')
        txt = open(p, encoding='utf-8', errors='replace').read()
        fm = parse_fm(txt)
        docs.append({
            'path': rel, 'top': rel.split('/')[0],
            'title': fm.get('title') or f[:-3],
            'type': fm.get('type', '?'), 'status': fm.get('status', '?'),
            'model': fm.get('model', ''), 'verdict': fm.get('verdict', ''),
            'updated': fm.get('updated', ''), 'summary': first_para(txt),
        })

tops = sorted({d['top'] for d in docs})
STATUS_ICON = {'active': '🟢', 'concluded': '⚪', 'dead': '❌', 'superseded': '🟡', 'archived': '📦', 'wip': '🚧'}

def link(d):
    return f"[[{d['path'][:-3]}|{d['title']}]]"

# per-folder MOC
for top in tops:
    rows = sorted([d for d in docs if d['top'] == top], key=lambda d: (d['path']))
    out = [f"# 🗂️ {top} — Map of Content", "",
           f"> Generated by `scripts/memory/build_index.py` — do not edit by hand. {len(rows)} docs.", ""]
    cur_sub = None
    for d in rows:
        sub = '/'.join(d['path'].split('/')[1:-1])
        if sub != cur_sub:
            cur_sub = sub
            out.append(f"\n### {sub or '(root)'}\n")
            out.append("| Doc | Type | Status | Verdict | Updated |")
            out.append("|---|---|---|---|---|")
        ic = STATUS_ICON.get(d['status'], '')
        out.append(f"| {link(d)} | {d['type']} | {ic} {d['status']} | {d['verdict']} | {d['updated']} |")
    open(f"{VAULT}/{top}/_MOC.md", 'w', encoding='utf-8', newline='\n').write('\n'.join(out) + '\n')

# Welcome hub
w = ["# 🧠 Vanguard Memory Vault", "",
     "> The shared memory for the Vanguard intraday trading engine. **This index is generated**",
     "> by `scripts/memory/build_index.py` from each doc's front-matter — do not hand-edit.",
     "> Protocol: [[00 — Start Here/AI Operating Protocol|AI Operating Protocol]] · "
     "Dead ends: [[00 — Start Here/Dead-Ends Register|Dead-Ends Register]] · "
     "Machine index: `00 — Start Here/INDEX.json`", "",
     f"**{len(docs)} docs** across {len(tops)} sections.", ""]
for top in tops:
    group = [d for d in docs if d['top'] == top]
    w.append(f"## {top}  ({len(group)})")
    w.append(f"→ [[{top}/_MOC|Browse all {len(group)}]]")
    # show active specs/reports/references inline (skip logs/archive detail)
    feat = [d for d in group if d['status'] in ('active', 'wip') and d['type'] in ('spec', 'report', 'reference', 'moc')]
    for d in sorted(feat, key=lambda d: d['path'])[:18]:
        w.append(f"- {link(d)} — {d['summary'][:90]}")
    w.append("")
open(f"{VAULT}/{START}/Welcome.md", 'w', encoding='utf-8', newline='\n').write('\n'.join(w) + '\n')

# INDEX.json
idx = [{k: d[k] for k in ('path', 'title', 'type', 'status', 'model', 'verdict', 'updated')} for d in sorted(docs, key=lambda d: d['path'])]
json.dump(idx, open(f"{VAULT}/{START}/INDEX.json", 'w', encoding='utf-8'), indent=1, ensure_ascii=False)

# Dead-Ends Register
dead = sorted([d for d in docs if d['status'] == 'dead'], key=lambda d: d['path'])
de = ["# ❌ Dead-Ends Register", "",
      "> Generated. Lines below are confirmed dead/closed — **do not re-attempt without new evidence.**", ""]
for d in dead:
    de.append(f"- {link(d)} {('('+d['verdict']+')') if d['verdict'] else ''} — {d['summary'][:120]}")
open(f"{VAULT}/{START}/Dead-Ends Register.md", 'w', encoding='utf-8', newline='\n').write('\n'.join(de) + '\n')

print(f"indexed {len(docs)} docs | MOCs={len(tops)} | dead-ends={len(dead)}")
print("generated: Welcome.md, INDEX.json, Dead-Ends Register.md,", ', '.join(f'{t}/_MOC.md' for t in tops))
