"""
OOS Dual-Model Backtest: v20 Rolling 1H + v3 15min Top-15% Gate
================================================================
Period: 2026-06-05 → 2026-06-18 (True OOS for both models)
Logic : Signal is generated by v20 (1H). Trade is only taken if
        the same ticker's score_15m is in the TOP 15% of the
        live cross-section at signal time (for LONG) or
        BOTTOM 15% (for SHORT) — mimicking the live orchestrator's
        _check_15m_percentile() call with top_percent=0.15.

Data source: data/vanguard_trades.db (live paper-trading log)
             score_15m is the v3 15min z-scored combined conviction
             already stored per-trade at signal time.

NOTE: The DB does NOT store the full cross-section at each scan,
      so we cannot recompute the exact percentile threshold.
      Instead we use the CLOSED-trades cross-section per scan
      timestamp (within ±5 min window) as a proxy, OR we use the
      score_15m value alone and apply the top/bottom 15% cut over
      the OOS universe of all signals that were attempted (which
      is a fair retrospective simulation of the filter).

Run:  python -m scripts.backtests.oos_dual_model_backtest
"""

import sqlite3
import pandas as pd
import numpy as np
from pathlib import Path
from datetime import datetime, timedelta

# ─── Config ───────────────────────────────────────────────────────────────────
DB_PATH         = "data/vanguard_trades.db"
OOS_START       = "2026-06-05"
TOP_PERCENT     = 0.15          # top-15% gate on score_15m
CAPITAL         = 99517.68
MARGIN_MULT     = 5.0           # 5x intraday margin
MAX_SLOTS       = 5
BROKERAGE_RT    = 20.0          # ₹20 round-trip
STT_RATE        = 0.00025       # 0.025% on sell side
SLIPPAGE_PCT    = 0.0003        # 0.03% per leg

# ─── Load Data ────────────────────────────────────────────────────────────────
conn = sqlite3.connect(DB_PATH)
df = pd.read_sql_query(
    f"""
    SELECT id, trade_id, timestamp, ticker, side,
           long_score, short_score, score_15m,
           entry_price, exit_price, final_profit_pct,
           net_pnl_amt, status, strategy_id,
           exit_time, stop_loss_pct, take_profit_pct,
           comment, is_ensemble
    FROM trades
    WHERE timestamp >= '{OOS_START}'
    ORDER BY timestamp
    """,
    conn
)
conn.close()

df["timestamp"] = pd.to_datetime(df["timestamp"])
df["exit_time"]  = pd.to_datetime(df["exit_time"])
df["trade_date"] = df["timestamp"].dt.date

print(f"\n{'='*70}")
print(f"  TRUE OOS DUAL-MODEL BACKTEST  |  v20 1H + v3 15min Top-{int(TOP_PERCENT*100)}% Gate")
print(f"  Period: {OOS_START} → {df['timestamp'].max().date()}")
print(f"{'='*70}\n")

# ─── Step 1: Universe — all signals that were attempted (any status except
#             pure system artefacts). We exclude CANCELLED (no fill) and keep
#             CLOSED, VETOED, VETOED_EXPIRED so we can see what the models
#             originally selected.
# For the 15m filter we work on the FULL attempted universe so the
# percentile cut is computed over a fair cross-section per scan.
# ─────────────────────────────────────────────────────────────────────────────

ALL_STATUSES = ["CLOSED", "VETOED", "VETOED_EXPIRED", "CANCELLED",
                "STOP_LOSS", "TAKE_PROFIT"]

# All rows that had a real model score (score_15m not null)
universe = df[df["score_15m"].notna()].copy()
print(f"[INFO] Total rows with score_15m in OOS period : {len(universe)}")
print(f"[INFO] Status breakdown:")
print(universe["status"].value_counts().to_string())
print()

# ─── Step 2: Apply top-15% gate per trading day & scan cluster
# We group by date and compute the rolling percentile within each day's
# cross-section (all tickers scored on the same day act as the universe).
# For LONG: score_15m must be >= 85th percentile of the day's distribution
# For SHORT: score_15m must be <= 15th percentile of the day's distribution
# ─────────────────────────────────────────────────────────────────────────────

filtered_rows = []
for date, day_df in universe.groupby("trade_date"):
    scores = day_df["score_15m"]
    long_thresh  = scores.quantile(1.0 - TOP_PERCENT)   # 85th pct
    short_thresh = scores.quantile(TOP_PERCENT)           # 15th pct

    for _, row in day_df.iterrows():
        s15 = row["score_15m"]
        side = row["side"]
        if side == "LONG":
            passes = s15 >= long_thresh
        else:
            passes = s15 <= short_thresh

        row_dict = row.to_dict()
        row_dict["_15m_long_thresh"]  = long_thresh
        row_dict["_15m_short_thresh"] = short_thresh
        row_dict["_15m_passes"]       = passes
        filtered_rows.append(row_dict)

filtered = pd.DataFrame(filtered_rows)

passed_filter = filtered[filtered["_15m_passes"]].copy()
failed_filter = filtered[~filtered["_15m_passes"]].copy()

print(f"[FILTER] Signals passing top-{int(TOP_PERCENT*100)}% gate : {len(passed_filter)}")
print(f"[FILTER] Signals blocked by gate                  : {len(failed_filter)}")
print()

# ─── Step 3: Build trade-level PnL for CLOSED / SL / TP trades that pass gate
# We treat CANCELLED as "no trade" (no fill).
# We treat VETOED / VETOED_EXPIRED as "trade was blocked by AI" — we
# report them separately as counterfactual.
# ─────────────────────────────────────────────────────────────────────────────

FILLED_STATUSES = {"CLOSED", "STOP_LOSS", "TAKE_PROFIT"}

filled = passed_filter[passed_filter["status"].isin(FILLED_STATUSES)].copy()

# Compute realistic PnL with costs
def compute_trade_pnl(row):
    ep = row["entry_price"]
    xp = row["exit_price"] if row["exit_price"] else ep
    side = row["side"]
    pct_raw = row["final_profit_pct"] / 100.0   # convert % → fraction

    # Notional per trade (slot capital * margin)
    slot_capital = CAPITAL / MAX_SLOTS
    notional     = slot_capital * MARGIN_MULT
    shares       = int(notional / ep) if ep > 0 else 0
    if shares <= 0:
        return 0.0, 0.0, 0.0

    gross_pnl = shares * ep * pct_raw * (1 if side == "LONG" else 1)
    sell_val  = shares * xp
    stt       = sell_val * STT_RATE
    slippage  = (shares * ep * SLIPPAGE_PCT) + (shares * xp * SLIPPAGE_PCT)
    total_cost = BROKERAGE_RT + stt + slippage
    net_pnl    = gross_pnl - total_cost

    return gross_pnl, total_cost, net_pnl

gross_list, cost_list, net_list, shares_list = [], [], [], []
for _, row in filled.iterrows():
    ep = row["entry_price"]
    slot_capital = CAPITAL / MAX_SLOTS
    notional     = slot_capital * MARGIN_MULT
    sh = int(notional / ep) if ep > 0 else 0
    g, c, n = compute_trade_pnl(row)
    gross_list.append(g)
    cost_list.append(c)
    net_list.append(n)
    shares_list.append(sh)

filled["_gross_pnl"] = gross_list
filled["_costs"]     = cost_list
filled["_net_pnl"]   = net_list
filled["_shares"]    = shares_list

# ─── Step 4: Session (Day) Level Aggregation
# ─────────────────────────────────────────────────────────────────────────────

def session_stats(df_f):
    if df_f.empty:
        return pd.DataFrame()
    agg = df_f.groupby("trade_date").agg(
        trades      = ("_net_pnl", "count"),
        gross_pnl   = ("_gross_pnl", "sum"),
        total_costs = ("_costs", "sum"),
        net_pnl     = ("_net_pnl", "sum"),
        winners     = ("_net_pnl", lambda x: (x > 0).sum()),
        losers      = ("_net_pnl", lambda x: (x <= 0).sum()),
        best_trade  = ("_net_pnl", "max"),
        worst_trade = ("_net_pnl", "min"),
        avg_pct     = ("final_profit_pct", "mean"),
    ).reset_index()
    agg["win_rate"] = (agg["winners"] / agg["trades"] * 100).round(1)
    return agg

daily = session_stats(filled)

# ─── Step 5: Cumulative equity curve
cum_pnl = filled.sort_values("timestamp")["_net_pnl"].cumsum()
filled["_cum_pnl"] = cum_pnl.values

# ─── Step 6: Max drawdown
cum_series = filled.sort_values("timestamp")["_net_pnl"].cumsum()
running_max = cum_series.cummax()
drawdown = cum_series - running_max
max_dd = drawdown.min()

# ─── Step 7: By-side breakdown
def side_stats(df_f, side_label):
    s = df_f[df_f["side"] == side_label]
    if s.empty:
        return {}
    wins   = (s["_net_pnl"] > 0).sum()
    losses = (s["_net_pnl"] <= 0).sum()
    return {
        "side":       side_label,
        "trades":     len(s),
        "net_pnl":    s["_net_pnl"].sum(),
        "win_rate":   wins / len(s) * 100,
        "avg_pct":    s["final_profit_pct"].mean(),
        "best":       s["_net_pnl"].max(),
        "worst":      s["_net_pnl"].min(),
    }

long_stats  = side_stats(filled, "LONG")
short_stats = side_stats(filled, "SHORT")

# ─── Step 8: All individual trade list
# ─────────────────────────────────────────────────────────────────────────────

trade_list = filled[[
    "timestamp", "ticker", "side", "entry_price", "exit_price",
    "final_profit_pct", "_shares", "_gross_pnl", "_costs", "_net_pnl",
    "_cum_pnl", "status", "stop_loss_pct", "take_profit_pct",
    "score_15m", "long_score", "short_score", "strategy_id",
    "_15m_long_thresh", "_15m_short_thresh"
]].copy()
trade_list.columns = [
    "Entry Time", "Ticker", "Side", "Entry ₹", "Exit ₹",
    "PnL%", "Qty", "Gross PnL ₹", "Costs ₹", "Net PnL ₹",
    "Cum PnL ₹", "Status", "SL%", "TP%",
    "score_15m", "long_score", "short_score", "Strategy",
    "15m_Long_Thresh", "15m_Short_Thresh"
]
trade_list["Entry Time"] = trade_list["Entry Time"].dt.strftime("%Y-%m-%d %H:%M")
trade_list = trade_list.sort_values("Entry Time").reset_index(drop=True)
trade_list.index += 1

# ─── Step 9: Counterfactual — vetoed trades that passed 15m gate
# ─────────────────────────────────────────────────────────────────────────────

vetoed_passed = passed_filter[
    passed_filter["status"].isin({"VETOED", "VETOED_EXPIRED"})
].copy()

# ─── PRINT RESULTS ────────────────────────────────────────────────────────────

TOTAL_NET   = filled["_net_pnl"].sum()
TOTAL_GROSS = filled["_gross_pnl"].sum()
TOTAL_COSTS = filled["_costs"].sum()
N_TRADES    = len(filled)
WIN_RATE    = (filled["_net_pnl"] > 0).sum() / N_TRADES * 100 if N_TRADES else 0
AVG_PCT     = filled["final_profit_pct"].mean()
ROC         = TOTAL_NET / CAPITAL * 100          # return on capital

print("╔══════════════════════════════════════════════════════════════════╗")
print("║            SYSTEM PERFORMANCE — FILLED TRADES                  ║")
print("╚══════════════════════════════════════════════════════════════════╝")
print(f"  Period            : {OOS_START} → {df['timestamp'].max().date()}")
print(f"  Filled Trades     : {N_TRADES}")
print(f"  Win Rate          : {WIN_RATE:.1f}%")
print(f"  Avg PnL%/trade    : {AVG_PCT:+.3f}%")
print(f"  Gross PnL         : ₹{TOTAL_GROSS:+,.2f}")
print(f"  Total Costs       : ₹{TOTAL_COSTS:,.2f}")
print(f"  Net PnL           : ₹{TOTAL_NET:+,.2f}")
print(f"  ROC (on ₹{CAPITAL:,.0f}) : {ROC:+.3f}%")
print(f"  Max Drawdown      : ₹{max_dd:,.2f}")
print()

print("─── By Side ─────────────────────────────────────────────────────────")
for stats in [long_stats, short_stats]:
    if not stats:
        continue
    print(f"  {stats['side']:5s} | Trades: {stats['trades']:3d} | "
          f"WR: {stats['win_rate']:5.1f}% | "
          f"Avg%: {stats['avg_pct']:+.3f}% | "
          f"Net: ₹{stats['net_pnl']:+,.2f} | "
          f"Best: ₹{stats['best']:+,.2f} | Worst: ₹{stats['worst']:+,.2f}")
print()

print("─── Daily Session PnL ───────────────────────────────────────────────")
if not daily.empty:
    print(f"  {'Date':<12} {'Trades':>6} {'Winners':>7} {'Losers':>6} {'WR%':>6} {'Net PnL ₹':>12} {'Avg%':>8}")
    print(f"  {'─'*12} {'─'*6} {'─'*7} {'─'*6} {'─'*6} {'─'*12} {'─'*8}")
    for _, r in daily.iterrows():
        print(f"  {str(r.trade_date):<12} {r.trades:>6} {r.winners:>7} "
              f"{r.losers:>6} {r.win_rate:>5.1f}% {r.net_pnl:>+12,.2f} {r.avg_pct:>+8.3f}%")
    print(f"  {'─'*12} {'─'*6} {'─'*7} {'─'*6} {'─'*6} {'─'*12} {'─'*8}")
    print(f"  {'TOTAL':<12} {daily.trades.sum():>6} {daily.winners.sum():>7} "
          f"{daily.losers.sum():>6} {WIN_RATE:>5.1f}% {TOTAL_NET:>+12,.2f}")
print()

print("─── All Individual Trades ───────────────────────────────────────────")
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 200)
pd.set_option("display.float_format", lambda x: f"{x:+.3f}")
print(trade_list[["Entry Time", "Ticker", "Side", "Entry ₹", "Exit ₹",
                   "PnL%", "Net PnL ₹", "Cum PnL ₹", "Status",
                   "score_15m"]].to_string())
print()

print("─── Counterfactual: AI-Vetoed trades that passed 15m gate ──────────")
print(f"  {len(vetoed_passed)} trades vetoed by AI after passing 15m gate")
if not vetoed_passed.empty:
    cf = vetoed_passed[["timestamp", "ticker", "side", "entry_price",
                         "exit_price", "final_profit_pct", "score_15m",
                         "status"]].copy()
    cf["timestamp"] = cf["timestamp"].dt.strftime("%Y-%m-%d %H:%M")
    cf["final_profit_pct"] = cf["final_profit_pct"].map(lambda x: f"{x:+.4f}%")
    cf.columns = ["Entry Time", "Ticker", "Side", "Entry ₹", "Exit ₹",
                  "PnL% (if taken)", "score_15m", "Status"]
    cf.index = range(1, len(cf) + 1)
    print(cf.to_string())
print()

# ─── Save outputs
OUT_DIR = Path("data/backtests")
OUT_DIR.mkdir(parents=True, exist_ok=True)
stamp = datetime.now().strftime("%Y%m%d_%H%M")

trades_csv = OUT_DIR / f"oos_dual_model_trades_{stamp}.csv"
trade_list.to_csv(trades_csv, index=True)

daily_csv = OUT_DIR / f"oos_dual_model_daily_{stamp}.csv"
daily.to_csv(daily_csv, index=False)

if not vetoed_passed.empty:
    cf_csv = OUT_DIR / f"oos_dual_model_vetoed_cf_{stamp}.csv"
    vetoed_passed.to_csv(cf_csv, index=False)
    print(f"[SAVED] Counterfactual vetoes → {cf_csv}")

print(f"[SAVED] Trade list  → {trades_csv}")
print(f"[SAVED] Daily PnL   → {daily_csv}")
print()

# ─── FILTER IMPACT ANALYSIS ───────────────────────────────────────────────────
print("╔══════════════════════════════════════════════════════════════════╗")
print("║           15m FILTER IMPACT ANALYSIS                           ║")
print("╚══════════════════════════════════════════════════════════════════╝")

# What would have happened WITHOUT the 15m filter?
all_filled = df[df["status"].isin(FILLED_STATUSES)].copy()
all_gross_l, all_cost_l, all_net_l = [], [], []
for _, row in all_filled.iterrows():
    g, c, n = compute_trade_pnl(row)
    all_gross_l.append(g); all_cost_l.append(c); all_net_l.append(n)
all_filled["_net_pnl"] = all_net_l

no_filter_net    = sum(all_net_l)
no_filter_n      = len(all_filled)
no_filter_wr     = (all_filled["_net_pnl"] > 0).sum() / no_filter_n * 100 if no_filter_n else 0

print(f"  Without 15m filter: {no_filter_n} filled trades | "
      f"WR {no_filter_wr:.1f}% | Net ₹{no_filter_net:+,.2f}")
print(f"  With 15% gate     : {N_TRADES} filled trades | "
      f"WR {WIN_RATE:.1f}% | Net ₹{TOTAL_NET:+,.2f}")
print(f"  Filter removed    : {no_filter_n - N_TRADES} trades")
print(f"  PnL delta         : ₹{TOTAL_NET - no_filter_net:+,.2f} "
      f"({'BETTER' if TOTAL_NET > no_filter_net else 'WORSE'} with filter)")
print()
print("  Note: 'Without filter' uses only DB-closed trades (already through")
print("  AI veto). The 15m filter in the live system fires BEFORE AI veto.")
print("  Trades blocked by 15m in live trading never reached the AI stage.")
print()
