"""
TODAY's Top-1 Long + Top-1 Short  |  v20_rolling_1h  |  1-hour hold
===================================================================
Reproduces the LIVE signal layer for the current session ONLY, as the user
asked: at every 15-minute anchor from 10:15 to 14:15 IST, emit the single
best LONG (max long_score) and single best SHORT (max short_score) from the
active v20_rolling_1h ranker, hold each for exactly 1 hour, and score the P&L.

This is the pure signal stream (SIGNAL_RAW_SCORE_ONLY + ENTRY_TOP_K=1, daily
gate OFF, 15m gate OFF — the live config in scripts/vanguard/config.py). It
deliberately applies NO veto layers (Kronos/Gemini/candle), NO ATR stop, and
NO 5-slot cap — every top-1 pick per anchor is taken and held full 1h. That is
exactly the "trades that would be generated by top1 on short and long" and is
independent of the live shadow-trade log.

Parity: uses the SAME feature pipeline the live engine feeds v20 —
feature_utils.build_rolling_1h_ohlcv + compute_features(legacy=False) + the 4
per-scan cross-sectional features (Market_Mean_Return / Relative_Return /
Market_Mean_Volatility / Relative_Volatility). v20's 86-feature set contains no
Nifty/VIX/sector/daily inputs, so this reproduces the live scores exactly.

Data: no-auth Upstox v3 15-min candles (historical + today's intraday).

Run: python -m scripts.backtests.today_top1_1h_backtest
"""

import os, sys, json, time, urllib.parse, datetime as dt, warnings
import concurrent.futures as cf
sys.path.insert(0, os.getcwd())
warnings.filterwarnings("ignore")

import requests
import numpy as np
import pandas as pd
import xgboost as xgb

from scripts.tickers import TICKERS
from scripts.feature_utils import build_rolling_1h_ohlcv, compute_features

# ── CONFIG ──────────────────────────────────────────────────────────────────
TODAY        = dt.date.today()
ENTRY_FROM   = "10:15"      # first entry anchor (config.FIRST_ENTRY_TIME)
ENTRY_TO     = "14:15"      # last entry anchor  (config.LAST_ENTRY_TIME)
HOLD         = pd.Timedelta(hours=1)

V20_LONG  = "models/research/v20_rolling_1h/xgb_long_model.json"
V20_SHORT = "models/research/v20_rolling_1h/xgb_short_model.json"
V20_META  = "models/research/v20_rolling_1h/metadata.json"

# Cost views (round-trip). 6bps = current signal-layer research standard; 10bps
# = conservative. Rupee P&L below uses the live statutory model.
COST_BPS_PRIMARY = 6
COST_BPS_CONSERV = 10

# Live sizing (config.py). MAX_SLOTS caps CONCURRENT positions (a signal is
# dropped when every slot is busy); each slot deploys CAPITAL/MAX_SLOTS margin
# at MARGIN leverage. Override on the CLI:  python -m ... <slots> <leverage>
CAPITAL   = 99517.68
MAX_SLOTS = int(sys.argv[1]) if len(sys.argv) > 1 else 5
MARGIN    = float(sys.argv[2]) if len(sys.argv) > 2 else 5.0
SLOT_CAP  = CAPITAL / MAX_SLOTS
BROKERAGE_RT = 20.0     # Rs10 buy + Rs10 sell
STT_RATE     = 0.00025  # 0.025% sell side
SLIP_PCT     = 0.0003   # 0.03% per leg

CACHE = os.path.join(
    os.environ.get("TEMP", "/tmp"), "claude",
    "c--Users-loq-Desktop-Trading-finalgo",
    "today_top1_15m_cache")
os.makedirs(CACHE, exist_ok=True)

HDR = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
       "Accept": "application/json"}

INSTR = json.load(open("scripts/instrument_cache.json"))


# ── DATA FETCH (no-auth Upstox v3) ──────────────────────────────────────────
def fetch_15m(ticker):
    """Fetch ~25d historical + today's intraday 15-min candles. Cached per day."""
    sym = ticker.replace(".NS", "")
    ik = INSTR.get(sym)
    if not ik:
        return ticker, None
    cache_f = os.path.join(CACHE, f"{sym}_{TODAY}.csv")
    if os.path.exists(cache_f):
        df = pd.read_csv(cache_f, parse_dates=["timestamp"])
    else:
        enc = urllib.parse.quote(ik, safe="")
        frm = TODAY - dt.timedelta(days=25)
        candles = []
        try:
            r = requests.get(
                f"https://api.upstox.com/v3/historical-candle/{enc}/minutes/15/{TODAY}/{frm}",
                headers=HDR, timeout=25).json()
            candles += r.get("data", {}).get("candles", [])
            r2 = requests.get(
                f"https://api.upstox.com/v3/historical-candle/intraday/{enc}/minutes/15",
                headers=HDR, timeout=25).json()
            candles += r2.get("data", {}).get("candles", [])
        except Exception as e:
            return ticker, None
        if not candles:
            return ticker, None
        df = pd.DataFrame(candles, columns=["timestamp", "open", "high", "low", "close", "volume", "oi"])
        df["timestamp"] = pd.to_datetime(df["timestamp"]).dt.tz_localize(None)
        df = df.drop_duplicates("timestamp", keep="last").sort_values("timestamp")
        df.to_csv(cache_f, index=False)
    df = df.set_index("timestamp").rename(columns={
        "open": "Open", "high": "High", "low": "Low", "close": "Close", "volume": "Volume"})
    df = df[["Open", "High", "Low", "Close", "Volume"]].dropna()
    return ticker, df


# ── LOAD MODELS ─────────────────────────────────────────────────────────────
print("=" * 74)
print(f"  TODAY TOP-1 L/S BACKTEST  |  v20_rolling_1h  |  1h hold  |  {TODAY}")
print("=" * 74)
v20_feats = json.load(open(V20_META))["features"]
bst_l = xgb.Booster(); bst_l.load_model(V20_LONG)
bst_s = xgb.Booster(); bst_s.load_model(V20_SHORT)
print(f"[1/4] Models loaded — v20 features: {len(v20_feats)}")

# ── FETCH ───────────────────────────────────────────────────────────────────
print(f"[2/4] Fetching 15-min candles for {len(TICKERS)} tickers (no-auth v3)...")
raw15 = {}
with cf.ThreadPoolExecutor(max_workers=8) as ex:
    for tk, df in ex.map(fetch_15m, TICKERS):
        if df is not None and len(df) >= 40 and (df.index.date == TODAY).any():
            raw15[tk] = df
print(f"      {len(raw15)}/{len(TICKERS)} tickers have today's session data")

# ── BUILD FEATURES ──────────────────────────────────────────────────────────
print("[3/4] Building rolling-1h features (live pipeline parity)...")
feat = {}     # ticker -> feature DataFrame (v20 non-CS feats), indexed by anchor
close_1h = {} # ticker -> rolling-1h Close series (entry/exit prices), by anchor
for tk, df15 in raw15.items():
    try:
        h1 = build_rolling_1h_ohlcv(df15)
        if len(h1) < 20:
            continue
        f = compute_features(h1[["Open", "High", "Low", "Close", "Volume"]].copy(), legacy=False)
        feat[tk] = f
        close_1h[tk] = h1["Close"]
    except Exception:
        continue
print(f"      {len(feat)} tickers with v20 features ready")

# Anchors: today's rolling-1h timestamps in the entry window [10:15, 14:15]
anchor_set = set()
for f in feat.values():
    for tsx in f.index:
        if tsx.date() == TODAY and ENTRY_FROM <= tsx.strftime("%H:%M") <= ENTRY_TO:
            anchor_set.add(tsx)
anchors = sorted(anchor_set)
print(f"      {len(anchors)} entry anchors: {[a.strftime('%H:%M') for a in anchors]}")


# ── SCORING (parity with model_inference.score_universe + orchestrator CS) ──
def score_anchor(ts):
    rows, tickers = [], []
    for tk, f in feat.items():
        if ts in f.index:
            rows.append(f.loc[ts])
            tickers.append(tk)
    if len(tickers) < 10:
        return None
    X = pd.DataFrame(rows, index=tickers)
    # 4 per-scan cross-sectional features (orchestrator.py:1102-1105)
    X["Market_Mean_Return"] = X["Return"].mean()
    X["Relative_Return"] = X["Return"] - X["Market_Mean_Return"]
    X["Market_Mean_Volatility"] = X["HL_Range"].mean()
    X["Relative_Volatility"] = X["HL_Range"] / (X["Market_Mean_Volatility"] + 1e-8)
    Xm = np.nan_to_num(X[v20_feats].values.astype(np.float32))
    dm = xgb.DMatrix(Xm, feature_names=v20_feats)
    long_score = bst_l.predict(dm)
    short_score = bst_s.predict(dm)
    return pd.DataFrame({"ticker": tickers, "long_score": long_score, "short_score": short_score})


def exit_price(tk, ts):
    """1h-later rolling-1h close (= 15m close at ts+60m); fallback nearest >= exit."""
    s = close_1h[tk]
    ex_ts = ts + HOLD
    if ex_ts in s.index:
        return float(s.loc[ex_ts]), ex_ts, "TIME"
    after = s[s.index >= ex_ts]
    if not after.empty:
        return float(after.iloc[0]), after.index[0], "TIME"
    # no bar 1h out (shouldn't happen for <=14:15 entries) -> last available today
    same = s[s.index.date == ts.date()]
    return float(same.iloc[-1]), same.index[-1], "EOD"


# ── SIMULATE ────────────────────────────────────────────────────────────────
print(f"[4/4] Top-1 long + top-1 short per anchor, 1h hold — "
      f"{MAX_SLOTS} slots @ {MARGIN:.0f}x...\n")
trades = []
open_exit_ts = []   # exit timestamps of currently-open slots
dropped = 0
for ts in anchors:
    # free slots whose 1h hold has completed at/at-before this anchor
    open_exit_ts = [x for x in open_exit_ts if x > ts]
    sc = score_anchor(ts)
    if sc is None:
        continue
    for side in ("LONG", "SHORT"):
        col = "long_score" if side == "LONG" else "short_score"
        best = sc.sort_values(col, ascending=False).iloc[0]
        tk = best["ticker"]
        ep = float(close_1h[tk].loc[ts])
        if ep <= 0:
            continue
        if len(open_exit_ts) >= MAX_SLOTS:   # all slots busy -> signal dropped
            dropped += 1
            continue
        xp, xts, reason = exit_price(tk, ts)
        open_exit_ts.append(ts + HOLD)
        gross = (xp - ep) / ep if side == "LONG" else (ep - xp) / ep
        qty = int((SLOT_CAP * MARGIN) / ep)
        notional = qty * ep
        # realistic statutory cost (rupees): brokerage + STT(sell) + slippage 2 legs.
        # STT hits the SELL leg: exit for a LONG (qty*xp), entry for a SHORT (notional).
        stt = STT_RATE * (qty * xp if side == "LONG" else notional)
        slip = SLIP_PCT * notional * 2
        cost_inr = BROKERAGE_RT + stt + slip
        gross_inr = gross * notional
        net_inr = gross_inr - cost_inr
        trades.append({
            "entry_time": ts, "exit_time": xts, "ticker": tk.replace(".NS", ""),
            "side": side, "entry_px": round(ep, 2), "exit_px": round(xp, 2),
            "gross_bps": round(gross * 1e4, 2),
            "net6_bps": round(gross * 1e4 - COST_BPS_PRIMARY, 2),
            "net10_bps": round(gross * 1e4 - COST_BPS_CONSERV, 2),
            "long_score": round(float(best["long_score"]), 4),
            "short_score": round(float(best["short_score"]), 4),
            "qty": qty, "net_inr": round(net_inr, 2), "reason": reason,
        })

df = pd.DataFrame(trades)
if df.empty:
    print("No trades generated (no session data yet?).")
    sys.exit(0)
df = df.sort_values("entry_time").reset_index(drop=True)
df.index += 1


# ── REPORT ──────────────────────────────────────────────────────────────────
def block(sdf, label):
    n = len(sdf)
    if n == 0:
        return
    wr = (sdf["gross_bps"] > 0).mean() * 100
    print(f"  {label:6s} n={n:2d}  WR={wr:4.0f}%  "
          f"gross={sdf['gross_bps'].mean():+7.2f}bps  "
          f"net@6={sdf['net6_bps'].mean():+7.2f}  net@10={sdf['net10_bps'].mean():+7.2f}bps  "
          f"net Rs={sdf['net_inr'].sum():+9.2f}")

SEP = "-" * 74
show = df.copy()
show["entry_time"] = show["entry_time"].dt.strftime("%H:%M")
show["exit_time"] = show["exit_time"].dt.strftime("%H:%M")
pd.set_option("display.width", 240); pd.set_option("display.max_columns", None)
print(SEP); print("  ALL TRADES"); print(SEP)
print(show[["entry_time", "exit_time", "ticker", "side", "entry_px", "exit_px",
            "gross_bps", "net6_bps", "net10_bps", "qty", "net_inr"]].to_string())
print()
print(SEP); print("  SUMMARY  (per-trade means, bps = 1/100 of a %)"); print(SEP)
block(df, "ALL")
block(df[df.side == "LONG"], "LONG")
block(df[df.side == "SHORT"], "SHORT")
print(SEP)
print(f"  Book net @6bps : Rs {df['net_inr'].sum():+,.2f}   "
      f"(gross {df['gross_bps'].mean():+.2f}bps/trade over {len(df)} trades)")
print(f"  Sizing: {MAX_SLOTS} slots x Rs{SLOT_CAP:,.0f}/slot x {MARGIN:.0f} leverage = "
      f"Rs{SLOT_CAP*MARGIN:,.0f} notional/trade; max book Rs{CAPITAL*MARGIN:,.0f}.")
print(f"  Signals dropped (all slots busy): {dropped}")
print(f"  NOTE: pure top-1 signal stream — no veto layers, no ATR stop. Live")
print(f"        enforce-mode (Kronos veto + candle guard + 2xATR stop) would alter fills.")
print(SEP)

out = f"data/backtests/today_top1_1h_{TODAY}.csv"
os.makedirs("data/backtests", exist_ok=True)
df.to_csv(out)
print(f"[SAVED] {out}")
