# Sector classification for all 172 NSE tickers
# Used by prepare_data_v3.py to compute sector momentum features
#
# Sectors based on GICS/BSE classification:
#   BANK, IT, PHARMA, AUTO, METAL, ENERGY, FMCG, FINANCE,
#   CEMENT, REALTY, INFRA, CHEMICAL, CONSUMER, TELECOM, DEFENCE, MISC

SECTOR_MAP = {
    # ── BANKING ───────────────────────────────────────────────────────────────
    "HDFCBANK.NS":   "BANK",
    "ICICIBANK.NS":  "BANK",
    "SBIN.NS":       "BANK",
    "AXISBANK.NS":   "BANK",
    "INDUSINDBK.NS": "BANK",
    "BANKBARODA.NS": "BANK",
    "CANBK.NS":      "BANK",
    "PNB.NS":        "BANK",
    "FEDERALBNK.NS": "BANK",
    "IDFCFIRSTB.NS": "BANK",
    "AUBANK.NS":     "BANK",
    "BANDHANBNK.NS": "BANK",
    "RBLBANK.NS":    "BANK",

    # ── IT / TECH ─────────────────────────────────────────────────────────────
    "TCS.NS":        "IT",
    "INFY.NS":       "IT",
    "HCLTECH.NS":    "IT",
    "WIPRO.NS":      "IT",
    "TECHM.NS":      "IT",
    "MPHASIS.NS":    "IT",
    "OFSS.NS":       "IT",
    "PERSISTENT.NS": "IT",
    "COFORGE.NS":    "IT",
    "LTTS.NS":       "IT",
    "NAUKRI.NS":     "IT",

    # ── PHARMA / HEALTHCARE ───────────────────────────────────────────────────
    "SUNPHARMA.NS":  "PHARMA",
    "DRREDDY.NS":    "PHARMA",
    "CIPLA.NS":      "PHARMA",
    "DIVISLAB.NS":   "PHARMA",
    "ALKEM.NS":      "PHARMA",
    "LUPIN.NS":      "PHARMA",
    "AUROPHARMA.NS": "PHARMA",
    "BIOCON.NS":     "PHARMA",
    "TORNTPHARM.NS": "PHARMA",
    "LAURUSLABS.NS": "PHARMA",
    "GRANULES.NS":   "PHARMA",
    "SYNGENE.NS":    "PHARMA",
    "LALPATHLAB.NS": "PHARMA",
    "METROPOLIS.NS": "PHARMA",
    "APOLLOHOSP.NS": "PHARMA",

    # ── AUTO ──────────────────────────────────────────────────────────────────
    "MARUTI.NS":     "AUTO",
    "M&M.NS":        "AUTO",
    "BAJAJ-AUTO.NS": "AUTO",
    "EICHERMOT.NS":  "AUTO",
    "HEROMOTOCO.NS": "AUTO",
    "TVSMOTOR.NS":   "AUTO",
    "MOTHERSON.NS":  "AUTO",
    "BOSCHLTD.NS":   "AUTO",
    "APOLLOTYRE.NS": "AUTO",
    "MRF.NS":        "AUTO",
    "BALKRISIND.NS": "AUTO",
    "BHARATFORG.NS": "AUTO",
    "ESCORTS.NS":    "AUTO",
    "EXIDEIND.NS":   "AUTO",

    # ── METALS / MINING ───────────────────────────────────────────────────────
    "TATASTEEL.NS":  "METAL",
    "JSWSTEEL.NS":   "METAL",
    "HINDALCO.NS":   "METAL",
    "VEDL.NS":       "METAL",
    "JINDALSTEL.NS": "METAL",
    "COALINDIA.NS":  "METAL",
    "SAIL.NS":       "METAL",
    "NMDC.NS":       "METAL",

    # ── ENERGY / OIL & GAS ────────────────────────────────────────────────────
    "RELIANCE.NS":   "ENERGY",
    "ONGC.NS":       "ENERGY",
    "BPCL.NS":       "ENERGY",
    "IOC.NS":        "ENERGY",
    "GAIL.NS":       "ENERGY",
    "PETRONET.NS":   "ENERGY",
    "IGL.NS":        "ENERGY",
    "NTPC.NS":       "ENERGY",
    "POWERGRID.NS":  "ENERGY",
    "TATAPOWER.NS":  "ENERGY",
    "ADANIPOWER.NS": "ENERGY",
    "ADANIGREEN.NS": "ENERGY",
    "RECLTD.NS":     "ENERGY",
    "PFC.NS":        "ENERGY",

    # ── FMCG ──────────────────────────────────────────────────────────────────
    "HINDUNILVR.NS": "FMCG",
    "ITC.NS":        "FMCG",
    "BRITANNIA.NS":  "FMCG",
    "NESTLEIND.NS":  "FMCG",
    "TATACONSUM.NS": "FMCG",
    "GODREJCP.NS":   "FMCG",
    "DABUR.NS":      "FMCG",
    "MARICO.NS":     "FMCG",
    "COLPAL.NS":     "FMCG",
    "VBL.NS":        "FMCG",
    "JUBLFOOD.NS":   "FMCG",
    "DEVYANI.NS":    "FMCG",

    # ── FINANCE (Non-Bank) ────────────────────────────────────────────────────
    "BAJFINANCE.NS": "FINANCE",
    "BAJAJFINSV.NS": "FINANCE",
    "SBILIFE.NS":    "FINANCE",
    "HDFCLIFE.NS":   "FINANCE",
    "SBICARD.NS":    "FINANCE",
    "CHOLAFIN.NS":   "FINANCE",
    "ICICIGI.NS":    "FINANCE",
    "ICICIPRULI.NS": "FINANCE",
    "MFSL.NS":       "FINANCE",
    "M&MFIN.NS":     "FINANCE",
    "MUTHOOTFIN.NS": "FINANCE",
    "MANAPPURAM.NS": "FINANCE",
    "SHRIRAMFIN.NS": "FINANCE",
    "SUNDARMFIN.NS": "FINANCE",
    "ABCAPITAL.NS":  "FINANCE",
    "STARHEALTH.NS": "FINANCE",
    "PAYTM.NS":      "FINANCE",
    "POLICYBZR.NS":  "FINANCE",
    "NYKAA.NS":      "FINANCE",

    # ── CEMENT ────────────────────────────────────────────────────────────────
    "ULTRACEMCO.NS": "CEMENT",
    "SHREECEM.NS":   "CEMENT",
    "AMBUJACEM.NS":  "CEMENT",
    "GRASIM.NS":     "CEMENT",
    "JKCEMENT.NS":   "CEMENT",
    "DALBHARAT.NS":  "CEMENT",
    "RAMCOCEM.NS":   "CEMENT",

    # ── REALTY ────────────────────────────────────────────────────────────────
    "DLF.NS":        "REALTY",
    "OBEROIRLTY.NS": "REALTY",
    "GODREJPROP.NS": "REALTY",
    "PRESTIGE.NS":   "REALTY",
    "PHOENIXLTD.NS": "REALTY",
    "BRIGADE.NS":    "REALTY",

    # ── INFRA / CAPITAL GOODS ─────────────────────────────────────────────────
    "LT.NS":         "INFRA",
    "ADANIENT.NS":   "INFRA",
    "ADANIPORTS.NS": "INFRA",
    "ATGL.NS":       "INFRA",
    "ABB.NS":        "INFRA",
    "SIEMENS.NS":    "INFRA",
    "HAVELLS.NS":    "INFRA",
    "POLYCAB.NS":    "INFRA",
    "CUMMINSIND.NS": "INFRA",
    "THERMAX.NS":    "INFRA",
    "KEC.NS":        "INFRA",
    "KPIL.NS":       "INFRA",
    "BHEL.NS":       "INFRA",
    "CONCOR.NS":     "INFRA",
    "IRCTC.NS":      "INFRA",
    "HAL.NS":        "INFRA",
    "BEL.NS":        "INFRA",
    "CROMPTON.NS":   "INFRA",
    "VOLTAS.NS":     "INFRA",
    "ASTRAL.NS":     "INFRA",
    "SCHAEFFLER.NS": "INFRA",
    "SKFINDIA.NS":   "INFRA",
    "TIMKEN.NS":     "INFRA",
    "AIAENG.NS":     "INFRA",
    "ARE&M.NS":      "INFRA",

    # ── CHEMICALS ─────────────────────────────────────────────────────────────
    "SRF.NS":        "CHEMICAL",
    "PIIND.NS":      "CHEMICAL",
    "UPL.NS":        "CHEMICAL",
    "DEEPAKNTR.NS":  "CHEMICAL",
    "AARTIIND.NS":   "CHEMICAL",
    "ATUL.NS":       "CHEMICAL",
    "NAVINFLUOR.NS": "CHEMICAL",
    "COROMANDEL.NS": "CHEMICAL",
    "CHAMBLFERT.NS": "CHEMICAL",
    "GNFC.NS":       "CHEMICAL",
    "TATACHEM.NS":   "CHEMICAL",
    "PIDILITIND.NS": "CHEMICAL",

    # ── CONSUMER / RETAIL / MEDIA ─────────────────────────────────────────────
    "TITAN.NS":      "CONSUMER",
    "TRENT.NS":      "CONSUMER",
    "PAGEIND.NS":    "CONSUMER",
    "BATAINDIA.NS":  "CONSUMER",
    "RELAXO.NS":     "CONSUMER",
    "BERGEPAINT.NS": "CONSUMER",
    "WHIRLPOOL.NS":  "CONSUMER",
    "PVRINOX.NS":    "CONSUMER",
    "UNITDSPR.NS":   "CONSUMER",
    "AWL.NS":        "CONSUMER",

    # ── TELECOM / MEDIA ──────────────────────────────────────────────────────
    "BHARTIARTL.NS": "TELECOM",
    "TATACOMM.NS":   "TELECOM",
    "INDIGO.NS":     "MISC",
    "SUNTV.NS":      "TELECOM",
    "ZEEL.NS":       "TELECOM",
    "DELHIVERY.NS":  "MISC",
}

# List of all sectors (for iteration)
SECTORS = sorted(set(SECTOR_MAP.values()))
