# List of NSE Tickers for Training and Trading
# Optimized for Vanguard V2.3 Stability

TICKERS = [
    # NIFTY 50 (Stable Symbols)
    "RELIANCE.NS", "TCS.NS", "HDFCBANK.NS", "ICICIBANK.NS", "INFY.NS", 
    "BHARTIARTL.NS", "HINDUNILVR.NS", "ITC.NS", "SBIN.NS", "LT.NS",
    "BAJFINANCE.NS", "AXISBANK.NS", "HCLTECH.NS", "MARUTI.NS", "SUNPHARMA.NS",
    "TITAN.NS", "TATASTEEL.NS", "ULTRACEMCO.NS", "NTPC.NS", "M&M.NS",
    "POWERGRID.NS", "BAJAJFINSV.NS", "ADANIENT.NS", "COALINDIA.NS", "ONGC.NS",
    "JSWSTEEL.NS", "ADANIPORTS.NS", "GRASIM.NS", "HINDALCO.NS",
    "DRREDDY.NS", "CIPLA.NS", "INDUSINDBK.NS", "TATACONSUM.NS", "WIPRO.NS",
    "NESTLEIND.NS", "TECHM.NS", "DIVISLAB.NS", "BRITANNIA.NS", "BAJAJ-AUTO.NS",
    "EICHERMOT.NS", "SBILIFE.NS", "APOLLOHOSP.NS", "HDFCLIFE.NS", "HEROMOTOCO.NS",
    "BPCL.NS",

    # NIFTY NEXT 50 / MIDCAP SELECT
    "HAL.NS", "BEL.NS", "VBL.NS", "CHOLAFIN.NS", "SIEMENS.NS",
    "TRENT.NS", "SBICARD.NS", "DLF.NS", "IOC.NS", "VEDL.NS",
    "PAYTM.NS", "NAUKRI.NS", "SHREECEM.NS", "AMBUJACEM.NS",
    "HAVELLS.NS", "GAIL.NS", "PIDILITIND.NS", "ABB.NS", "GODREJCP.NS",
    "DABUR.NS", "BANKBARODA.NS", "CANBK.NS", "PNB.NS", "SRF.NS",
    "MOTHERSON.NS", "ICICIGI.NS", "MARICO.NS", "TVSMOTOR.NS", "INDIGO.NS",
    "JINDALSTEL.NS", "ICICIPRULI.NS", "BERGEPAINT.NS", "BOSCHLTD.NS", "UNITDSPR.NS",
    "ALKEM.NS", "LUPIN.NS", "AUROPHARMA.NS", "BIOCON.NS", "TORNTPHARM.NS",
    "ADANIPOWER.NS", "ATGL.NS", "ADANIGREEN.NS", "AWL.NS", "ABCAPITAL.NS",
    "IRCTC.NS", "CONCOR.NS", "BHEL.NS", "SAIL.NS", "NMDC.NS",
    "RECLTD.NS", "PFC.NS", "PETRONET.NS", "PIIND.NS", "UPL.NS",
    "COLPAL.NS", "IGL.NS", "MPHASIS.NS", "OFSS.NS", "PERSISTENT.NS",
    "COFORGE.NS", "LTTS.NS", "TATACHEM.NS", "TATAPOWER.NS", "TATACOMM.NS",
    "VOLTAS.NS", "WHIRLPOOL.NS", "CROMPTON.NS", "POLYCAB.NS", "ASTRAL.NS",
    "OBEROIRLTY.NS", "GODREJPROP.NS", "PRESTIGE.NS", "PHOENIXLTD.NS", "BRIGADE.NS",
    "FEDERALBNK.NS", "IDFCFIRSTB.NS", "AUBANK.NS", "BANDHANBNK.NS", "RBLBANK.NS",
    "MFSL.NS", "M&MFIN.NS", "MUTHOOTFIN.NS", "MANAPPURAM.NS", "SHRIRAMFIN.NS",
    "SUNDARMFIN.NS", "PVRINOX.NS", "SUNTV.NS", "ZEEL.NS",
    "JUBLFOOD.NS", "DEVYANI.NS", "PAGEIND.NS", "BATAINDIA.NS",
    "RELAXO.NS", "MRF.NS", "BALKRISIND.NS", "BHARATFORG.NS", "ESCORTS.NS",
    "CUMMINSIND.NS", "SCHAEFFLER.NS", "SKFINDIA.NS", "TIMKEN.NS", "AIAENG.NS",
    "THERMAX.NS", "KEC.NS", "KPIL.NS", "DEEPAKNTR.NS", "AARTIIND.NS",
    "ATUL.NS", "NAVINFLUOR.NS", "COROMANDEL.NS", "CHAMBLFERT.NS", "GNFC.NS",
    "EXIDEIND.NS", "ARE&M.NS", "LAURUSLABS.NS", "GRANULES.NS", "SYNGENE.NS",
    "LALPATHLAB.NS", "METROPOLIS.NS", "APOLLOTYRE.NS", "JKCEMENT.NS", "DALBHARAT.NS",
    "RAMCOCEM.NS", "STARHEALTH.NS", "NYKAA.NS", "POLICYBZR.NS", "DELHIVERY.NS"
]
