import os
import sys
import json
from datetime import datetime
from flask import Flask, jsonify, render_template

# Add project root to path before importing local modules
sys.path.append(os.getcwd())

from scripts.database_manager import (
    get_trades_by_status, get_performance_stats, get_trades_for_ticker, 
    get_ticker_performance, get_detailed_performance, get_portfolio_summary,
    get_strategy_performance, get_trades_by_strategy, get_recent_trades
)
from scripts.ticker_intelligence import get_ticker_analysis
from scripts.tickers import TICKERS
from scripts.terminal_utils import log

# Configuration
template_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '../templates'))
log(f"[INFO] Using template directory: {template_dir}")
app = Flask(__name__, template_folder=template_dir)

@app.route('/')
def index():
    return render_template('vanguard_v2.html')

STRATEGY_DEFINITIONS = {
    0: {
        "name": "Core ML/AI Pipeline (Directional Alpha)",
        "logic": "Long_Conviction >= 0.20 or Short_Conviction >= 0.20 (and meeting raw directional model scores)",
        "bias": "BI-DIRECTIONAL",
        "description": "The primary machine learning pipeline of the Vanguard trading engine. It computes real-time, high-frequency directional conviction scores for NSE tickers using a 1-hour XGBoost model trained on multi-timeframe regime and technical features.",
        "entry": "Generates a LONG candidate if Net Long Conviction >= 0.20 (ranked top 2) OR if raw directional Long Score >= 0.40 (excluding top Net candidates, ranked top 2). Generates a SHORT candidate under identical parameters mapped to Short Conviction and Short Score. Signals are strictly filtered by the Daily Macro Gatekeeper (only long/short-eligible tickers in the top 40% of the daily gatekeeper models).",
        "exit": "Standard trailing stop-loss (1.5x completed 15m ATR, clamped to [0.30%, 1.50%]) and target profit (3.0x completed 15m ATR, clamped to [0.75%, 2.50%]). Maximum default holding period is 1 hour (60 minutes), subject to a maximum of 2 extensions of 1 hour each if momentum continues."
    },
    2: {
        "name": "Short-Side Specialist",
        "logic": "Short_Rank <= 5",
        "bias": "SHORT",
        "description": "Looks exclusively for high-velocity short setups on weak tickers during overall downtrends, targeting specific breakdown points.",
        "entry": "Short Rank <= 5 (Top 5 highest conviction bearish candidates generated by the ML pipeline). No additional indicators are required; it targets raw directional speed.",
        "exit": "Standard trailing stop-loss (1.5x completed 15m ATR, clamped [0.30%, 1.50%]) and target profit (3.0x completed 15m ATR, clamped [0.75%, 2.50%]) or 1-hour holding window."
    },
    8: {
        "name": "Opening Range Breakout",
        "logic": "Short_Rank <= 5 & Close <= Day Low + 0.2% (After 10:00 AM)",
        "bias": "SHORT",
        "description": "An intraday breakdown strategy targeting tickers with intense institutional selling pressure that breaks below their opening range.",
        "entry": "Short Rank <= 5 (bearish conviction in top 5) and price is within 0.2% of the day's low (confirming breakdown below the opening range). Active only after 10:00 AM.",
        "exit": "Standard trailing stop-loss (1.5x completed 15m ATR, clamped [0.30%, 1.50%]) and target profit (3.0x completed 15m ATR, clamped [0.75%, 2.50%]) or 1-hour holding window."
    },
    10: {
        "name": "Quad-Timeframe Unanimous",
        "logic": "Long_Rank <= 3 (Extreme Conviction)",
        "bias": "LONG",
        "description": "An extreme high-conviction trend-following strategy designed to ride secular buying pressure on top-ranked tickers with unanimous multi-timeframe alignment.",
        "entry": "Long Rank <= 3 (Top 3 highest conviction bullish candidates). Assumes strong alignment across major trend intervals (15m, 30m, 1h).",
        "exit": "Standard trailing stop-loss (1.5x completed 15m ATR, clamped [0.30%, 1.50%]) and target profit (3.0x completed 15m ATR, clamped [0.75%, 2.50%]) or 1-hour holding window."
    },
    18: {
        "name": "Volatility Expansion",
        "logic": "Short_Rank <= 3 & ATR > 1.5%",
        "bias": "SHORT",
        "description": "Capitalizes on rapid breakout velocity during volatility spikes where selling pressure accelerates past typical noise bands.",
        "entry": "Short Rank <= 3 (Top 3 bearish candidates) combined with 14-period 15m ATR > 1.5% of ticker close price (confirming large price expansion).",
        "exit": "Standard trailing stop-loss (1.5x completed 15m ATR, clamped [0.30%, 1.50%]) and target profit (3.0x completed 15m ATR, clamped [0.75%, 2.50%]) or 1-hour holding window."
    },
    19: {
        "name": "Low-Vol Grind",
        "logic": "Long_Rank <= 5 & IBS < 0.15",
        "bias": "LONG",
        "description": "Accumulation setup targeting strong bullish tickers experiencing temporary intraday pullbacks/exhaustion during overall uptrends.",
        "entry": "Long Rank <= 5 (Top 5 bullish candidates) and IBS (Intraday Bar Strength) < 0.15 (closing near the bottom of the current candle, indicating oversold intraday conditions).",
        "exit": "Standard trailing stop-loss (1.5x completed 15m ATR, clamped [0.30%, 1.50%]) and target profit (3.0x completed 15m ATR, clamped [0.75%, 2.50%]) or 1-hour holding window."
    },
    35: {
        "name": "Volatility Contraction",
        "logic": "Long_Rank <= 5 & ATR < 0.2%",
        "bias": "LONG",
        "description": "Squeeze accumulator entering positions on high-conviction bullish setups during periods of absolute quiet, anticipating an explosive breakout.",
        "entry": "Long Rank <= 5 (Top 5 bullish candidates) and 14-period 15m ATR < 0.2% (extreme low volatility contraction).",
        "exit": "Standard trailing stop-loss (1.5x completed 15m ATR, clamped [0.30%, 1.50%]) and target profit (3.0x completed 15m ATR, clamped [0.75%, 2.50%]) or 1-hour holding window."
    },
    36: {
        "name": "The Opening Drive",
        "logic": "Long_Rank <= 10 & Gap > 0.3% (Before 10:30 AM)",
        "bias": "LONG",
        "description": "Morning momentum drive designed to ride the early opening impulse of high-conviction tickers opening with upward gaps.",
        "entry": "Long Rank <= 10 (Top 10 bullish candidates), opening gap > 0.3% of previous close, executed during the market open window (before 10:30 AM).",
        "exit": "Standard trailing stop-loss (1.5x completed 15m ATR, clamped [0.30%, 1.50%]) and target profit (3.0x completed 15m ATR, clamped [0.75%, 2.50%]) or 1-hour holding window."
    },
    39: {
        "name": "The VWAP Pinch",
        "logic": "Long_Rank <= 3 & Price near MA20 & ATR < 0.2%",
        "bias": "LONG",
        "description": "Compression entry near short-term moving average support for high-conviction tickers, representing low-risk breakout entries.",
        "entry": "Long Rank <= 3 (Top 3 bullish candidates), 14-period 15m ATR < 0.2%, and absolute difference between current price and 20-period moving average < 0.2%.",
        "exit": "Standard trailing stop-loss (1.5x completed 15m ATR, clamped [0.30%, 1.50%]) and target profit (3.0x completed 15m ATR, clamped [0.75%, 2.50%]) or 1-hour holding window."
    },
    42: {
        "name": "Trend Exhaustion Trap",
        "logic": "Short_Rank <= 10 & IBS < 0.3",
        "bias": "SHORT",
        "description": "Counter-trend/reversal setup designed to trap late-day buyers on weak tickers experiencing fatigue.",
        "entry": "Short Rank <= 10 (Top 10 bearish candidates) and IBS (Intraday Bar Strength) < 0.3 (price failing to hold intraday highs, indicating overhead selling pressure).",
        "exit": "Standard trailing stop-loss (1.5x completed 15m ATR, clamped [0.30%, 1.50%]) and target profit (3.0x completed 15m ATR, clamped [0.75%, 2.50%]) or 1-hour holding window."
    }
}

@app.route('/api/strategies')
def get_strategies_data():
    try:
        perf = get_strategy_performance()
        return jsonify({
            'definitions': STRATEGY_DEFINITIONS,
            'performance': perf
        })
    except Exception as e:
        log(f"[ERROR] Strategy API Error: {e}")
        return jsonify({'error': str(e)}), 500


@app.route('/api/tickers')
def get_tickers():
    return jsonify([t.replace('.NS', '') for t in TICKERS])

@app.route('/api/upstox/stats')
def get_upstox_stats():
    """Returns full portfolio state: capital, margins, open positions, today's P&L."""
    stats_path = os.path.join(os.getcwd(), 'upstox_stats.json')
    
    # Load base stats from the engine's persisted JSON
    stats = None
    if os.path.exists(stats_path):
        try:
            with open(stats_path, 'r') as f:
                stats = json.load(f)
        except json.JSONDecodeError:
            log("[WARN] upstox_stats.json currently locked/malformed. Using defaults.")
            pass
            
    if stats is None:
        stats = {
            "initial_capital":      99517.68,
            "virtual_capital":      99517.68,
            "used_margin":          0.0,
            "available_margin":     99517.68,
            "realized_charges":     0.0,
            "open_positions_count": 0,
            "unrealized_pnl_inr":   0.0,
            "day_realized_pnl_inr": 0.0,
            "total_pnl_inr":        0.0,
            "total_pnl_pct":        0.0,
            "positions":            [],
            "timestamp":            datetime.now().isoformat(),
        }

    # Merge with live DB portfolio summary (wins, losses, today's closed trades)
    try:
        summary = get_portfolio_summary()
        stats['today_summary'] = summary
    except Exception as e:
        log(f"[WARN] Portfolio summary error: {e}")
        stats['today_summary'] = {
            'total_trades': 0, 'wins': 0, 'losses': 0, 'win_rate': 0.0,
            'net_pnl_inr': 0.0, 'best_trade_inr': 0.0, 'worst_trade_inr': 0.0,
            'avg_pnl_inr': 0.0, 'today_trades': []
        }

    return jsonify(stats)

@app.route('/performance')
def performance_page():
    return render_template('performance.html')

@app.route('/api/performance_data')
def performance_data():
    try:
        data = get_detailed_performance()
        return jsonify(data)
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@app.route('/api/upstox/orders')
def get_upstox_orders():
    try:
        from scripts.upstox_broker import UpstoxSandboxBroker
        broker = UpstoxSandboxBroker()
        orders = broker.get_order_book()
        
        # Handle Upstox SDK response objects
        if hasattr(orders, 'to_dict'):
            return jsonify(orders.to_dict())
        return jsonify(orders)
    except Exception as e:
        log(f"[ERROR] Order Book API Error: {e}")
        return jsonify({'error': str(e)}), 500

@app.route('/vanguard_status')
def get_vanguard_status():
    try:
        # Separate Open, Closed, and Vetoed trades for the UI
        open_trades = get_trades_by_status("OPEN", 20)
        pending_trades = get_trades_by_status("PENDING_ENTRY", 20)
        closed_trades = get_trades_by_status(["CLOSED", "STOP_LOSS", "TAKE_PROFIT"], 50)
        
        # Filter vetoed/cancelled trades to remove overlaps with open trades
        raw_vetoed = (
            get_trades_by_status(["VETOED", "CANCELLED"], 200) + 
            get_trades_by_status(["VETOED_EXPIRED", "CANCELLED_EXPIRED"], 500)
        )
        open_tickers = {t['ticker'] for t in open_trades}
        vetoed_trades = sorted([t for t in raw_vetoed if not (t['status'] in ['VETOED', 'CANCELLED'] and t['ticker'] in open_tickers)], 
                               key=lambda x: x.get('timestamp') or '', reverse=True)
        stats = get_performance_stats()
        
        return jsonify({
            'open_trades': open_trades,
            'pending_trades': pending_trades,
            'closed_trades': closed_trades,
            'vetoed_trades': vetoed_trades,
            'trades': get_recent_trades(100),
            'stats': stats,
            'system_health': 'ONLINE'
        })
    except Exception as e:
        log(f"[ERROR] Dashboard Data Error: {e}")
        return jsonify({'error': str(e), 'system_health': 'ERROR'})

@app.route('/live_scores')
def get_live_scores():
    try:
        if os.path.exists('data/latest_scores.json'):
            with open('data/latest_scores.json', 'r') as f:
                scores = json.load(f)
            return jsonify({'scores': scores})
        return jsonify({'scores': []})
    except Exception as e:
        return jsonify({'error': str(e)})

@app.route('/ticker/<symbol>')
def ticker_detail(symbol):
    try:
        # Sanitize symbol
        symbol = symbol.upper()
        if not symbol.endswith('.NS') and '.' not in symbol:
            symbol += '.NS'
            
        # 1. Fetch trade history
        history = get_trades_for_ticker(symbol, 20)
        
        # 2. Fetch performance stats
        perf = get_ticker_performance(symbol)
        
        # 3. Retrieve actual live price and multi-timeframe predictions
        live_price = None
        score_15m = 0.0
        score_30m = 0.0
        score_1h = 0.0
        score_1d = 0.0
        
        if os.path.exists('data/latest_scores.json'):
            try:
                with open('data/latest_scores.json', 'r') as f:
                    scores = json.load(f)
                ticker_data = next((s for s in scores if s['ticker'] == symbol), None)
                if ticker_data:
                    live_price = ticker_data.get('Close')
                    score_15m = ticker_data.get('score_15m', 0.0)
                    score_30m = ticker_data.get('score_30m', 0.0)
                    score_1h = ticker_data.get('Long_Conviction', 0.0)
                    score_1d = ticker_data.get('score_1d', 0.0)
            except Exception as e:
                log(f"[WARN] Failed to load scores/live price: {e}")
                
        if live_price is None:
            try:
                from scripts.upstox_broker import UpstoxSandboxBroker
                broker = UpstoxSandboxBroker()
                live_price = broker.get_live_price(symbol)
            except Exception as e:
                log(f"[WARN] Failed to fetch live price from broker for {symbol}: {e}")
        
        return render_template('ticker_detail.html', 
                             ticker=symbol, 
                             history=history, 
                             perf=perf,
                             live_price=live_price,
                             score_15m=score_15m,
                             score_30m=score_30m,
                             score_1h=score_1h,
                             score_1d=score_1d)
    except Exception as e:
        log(f"[ERROR] Ticker Detail Error: {e}")
        return f"Error loading detail page for {symbol}: {e}", 500

@app.route('/api/intelligence/<symbol>')
def get_intelligence(symbol):
    try:
        symbol = symbol.upper()
        # Basic history check to determine bias
        history = get_trades_for_ticker(symbol, 1)
        bias = history[0].get('side', 'NEUTRAL') if history else 'NEUTRAL'
        
        intelligence = get_ticker_analysis(symbol, bias)
        return jsonify(intelligence)
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@app.route('/api/model_snapshot')
def api_model_snapshot():
    """Returns current XGBoost model sentiment derived from conviction scores."""
    try:
        from scripts.market_tracker import get_model_snapshot
        return jsonify(get_model_snapshot())
    except Exception as e:
        log(f"[ERROR] Model Snapshot API Error: {e}")
        return jsonify({'error': str(e), 'overall_sentiment': 'UNAVAILABLE'}), 500

@app.route('/api/market_snapshot')
def api_market_snapshot():
    """Returns NIFTY 50 index data and market sentiment (cached 5 min)."""
    try:
        from scripts.market_tracker import get_market_snapshot
        return jsonify(get_market_snapshot())
    except Exception as e:
        log(f"[ERROR] Market Snapshot API Error: {e}")
        return jsonify({'error': str(e), 'market_sentiment': 'UNAVAILABLE'}), 500

@app.route('/strategy/<int:strategy_id>')
def strategy_detail(strategy_id):
    try:
        strat_def = STRATEGY_DEFINITIONS.get(strategy_id, {
            "name": f"Strategy {strategy_id}",
            "logic": "Logic description not available.",
            "bias": "UNKNOWN"
        })
        
        if strategy_id == 0:
            import sqlite3
            from scripts.database_manager import DB_PATH
            conn = sqlite3.connect(DB_PATH, timeout=10)
            conn.row_factory = sqlite3.Row
            cursor = conn.cursor()
            cursor.execute('SELECT * FROM trades WHERE strategy_id IS NULL ORDER BY timestamp DESC LIMIT 200')
            trades = [dict(row) for row in cursor.fetchall()]
            conn.close()
        else:
            trades = get_trades_by_strategy(strategy_id)
            
        return render_template('strategy_detail.html', 
                               strategy_id=strategy_id, 
                               strategy_def=strat_def,
                               trades=trades)
    except Exception as e:
        log(f"[ERROR] Strategy Detail Error: {e}")
        return f"Error loading strategy page: {e}", 500

if __name__ == '__main__':
    if not os.path.exists('data'): os.makedirs('data')
    log("============================================================")
    log("VANGUARD INTELLIGENCE DASHBOARD: http://127.0.0.1:5001")
    log("============================================================")
    app.run(debug=False, port=5001, host='0.0.0.0', threaded=True)
